version: "3"
services:
    db:
        image: "postgres:15.2-alpine"
        environment:
          POSTGRES_PASSWORD: example
          POSTGRES_USERNAME: snowdenmoses
          POSTGRES_DB: POSTGRES_DB
        restart: always
        ports:
          - "5432:5432"
        volumes:
          - ./pg-data:/var/lib/postgresql/data
    frontend:
        build:
          dockerfile: Dockerfile.dev
          context: ./frontend
        ports:
          - "3001:3000"
        volumes:
          - /app/node_modules
          - ./frontend:/app
    api:
        build:
          dockerfile: Dockerfile.dev
          context: ./server/findthatplug
        ports:
          - "3000:3000"
        volumes:
          - ./server/findthatplug:/app
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        depends_on:
          - db
volumes:
    pd-data:
    